# Generated by Django 4.2.10 on 2024-03-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_segment_sample_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='traits',
            options={'verbose_name_plural': 'Traits'},
        ),
    ]
