# Generated by Django 4.2.10 on 2024-03-04 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_audience_alter_traits_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.audience')),
            ],
        ),
    ]
