# Generated by Django 4.2.10 on 2024-03-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_answers_questions_remove_analyzereport_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.audience'),
        ),
    ]
