# Generated by Django 4.2.10 on 2024-03-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_questions_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzereport',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.segment'),
        ),
    ]
