# Generated by Django 4.2.10 on 2024-03-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_analyzereport_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeebackLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=200)),
            ],
        ),
    ]
