# Generated by Django 4.2.10 on 2024-03-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_feebackloop'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzereport',
            name='loop',
            field=models.BooleanField(default=False),
        ),
    ]
