# Generated by Django 4.2.10 on 2024-03-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_analyzereport_loop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeebackLoop',
        ),
    ]
