# Generated by Django 4.2.10 on 2024-03-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delete_feebackloop'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.audience'),
        ),
    ]
