# Generated by Django 4.2.10 on 2024-03-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_answers_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='audience',
        ),
    ]
