# Generated by Django 4.2.10 on 2024-03-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_audience_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='process_completed',
            field=models.BooleanField(default=False),
        ),
    ]
